--- 
title: "European Soccer Team Exploration"
author: "Sicheng Li, Weiyi Jiang and Xianmeng Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

  Modern football, largely believed to be born in England, nowadays widely considered the most popular sports across the world. In Europe, this game is playing an especially essential role in every community as a cultural signature. A lot of cities enjoy their great football reputation and therefore attract tourism and boost economy to a large extent, including Milan, Barcelona, Manchester, Munchen and so on. There are over 1000 clubs playing in over 37 leagues all across Europe, among which there are the so-called "big-5", the topmost league in England, Spain, Italy, Germany and France, attracting most spotlights around the world. The teams in these leagues are sharing the most part from the large independent economy. The 4 most valuable franchises in the world are currently each valued in excess of $3 billion. The rising ticket prices, growing commercial advertisements and profits by simply selling players are making managing a professional football club a remarkably lucrative venture.

  Modern football is played by two teams, 11 players each. Players are separated into strikers(ST), midfielders(MF), defenders(DF) and goalkeepers(GK). Only one GK at a time is allowed on the ground, who can touch the ball with hands in the penalty area. The formations of the team and the strategies of playing can be varied and sophisticated. The job of the head coach is to give instructions on the team, investigating the rivals and trying to make the best out of the current squads. 

  The International Association of Football (FIFA), formed in 1904, centralizes the sport’s governance and overall management,including modifying soccer rules, organizing the FIFA World Cup and coordinating events. It has grown to be one of the most effective steward of the sport globally.  

  In this project, we are going to use the data of the players and teams to analyze the skills of each player, cluster the players based on the attributes and explore playing style patterns of each team from their star players.













